#!/usr/bin/env python3
from __future__ import annotations

import subprocess
import sys
import textwrap
from pathlib import Path


def ensure_init(src_dir: Path) -> None:
    """Ensure src_dir/__init__.py exists."""
    init_file = src_dir / "__init__.py"
    if not init_file.exists():
        init_file.write_text("# Generated by piphelper\n", encoding="utf-8")


def create_cli_wrapper(
    project_root: Path,
    src_dir: Path,
    shell_entry: str,
) -> None:
    """
    Create Codebase/cli.py (or <src_dir>/cli.py) that runs the given shell script,
    usually 'run.sh' in the project root.
    """
    cli_file = src_dir / "cli.py"
    if cli_file.exists():
        # You can change this to overwrite or merge later if you want.
        return

    code = f"""\
    # Auto-generated by piphelper
    import subprocess
    from pathlib import Path
    import sys
    import os


    def main() -> None:
        # project root is one level above {src_dir.name}/
        root = Path(__file__).resolve().parents[1]
        script = root / "{shell_entry}"

        if not script.exists():
            print(f"[piphelper] Entry script '{{script}}' not found.", file=sys.stderr)
            sys.exit(1)

        if os.name != "nt":
            try:
                mode = script.stat().st_mode
                script.chmod(mode | 0o111)
            except Exception:
                pass

        try:
            result = subprocess.run([str(script)], check=False)
            sys.exit(result.returncode)
        except FileNotFoundError:
            print(f"[piphelper] Could not execute '{{script}}'.", file=sys.stderr)
            sys.exit(1)
    """

    cli_file.write_text(textwrap.dedent(code), encoding="utf-8")


def create_pyproject(
    project_root: Path,
    dist_name: str,
    version: str,
    description: str,
    author_name: str,
    author_email: str,
    src_dir_name: str,
    console_script_name: str,
) -> None:
    """
    Write a minimal pyproject.toml into project_root that:
    - Uses setuptools
    - Packages src_dir_name (e.g. Codebase)
    - Exposes a console script src_dir_name.cli:main
    """
    pyproject_path = project_root / "pyproject.toml"
    if pyproject_path.exists():
        raise FileExistsError(f"{pyproject_path} already exists; refusing to overwrite.")

    content = f"""\
    [build-system]
    requires = ["setuptools>=61.0", "wheel"]
    build-backend = "setuptools.build_meta"

    [project]
    name = "{dist_name}"
    version = "{version}"
    description = "{description}"
    authors = [{{ name = "{author_name}", email = "{author_email}" }}]
    readme = "README.md"
    requires-python = ">=3.9"
    dependencies = []

    [project.scripts]
    {console_script_name} = "{src_dir_name}.cli:main"

    [tool.setuptools.packages.find]
    where = ["."]
    include = ["{src_dir_name}*"]
    """

    pyproject_path.write_text(textwrap.dedent(content), encoding="utf-8")


def scaffold_project(
    project_root: Path,
    dist_name: str,
    src_dir_name: str = "Codebase",
    shell_entry: str = "run.sh",
    version: str = "0.1.0",
    description: str = "",
    author_name: str = "",
    author_email: str = "",
    console_script_name: str | None = None,
) -> None:
    """
    High-level helper for OTHER PROJECTS to call.

    - Ensures src_dir exists
    - Ensures __init__.py in src_dir
    - Creates <src_dir>/cli.py pointing to shell_entry
    - Writes pyproject.toml configured accordingly
    """
    project_root = project_root.resolve()
    src_dir = (project_root / src_dir_name).resolve()

    if not src_dir.exists():
        raise FileNotFoundError(f"Source dir '{src_dir}' does not exist.")

    ensure_init(src_dir)

    if console_script_name is None:
        console_script_name = dist_name

    create_cli_wrapper(
        project_root=project_root,
        src_dir=src_dir,
        shell_entry=shell_entry,
    )

    create_pyproject(
        project_root=project_root,
        dist_name=dist_name,
        version=version,
        description=description,
        author_name=author_name,
        author_email=author_email,
        src_dir_name=src_dir_name,
        console_script_name=console_script_name,
    )


def build_project(project_root: Path) -> int:
    """
    Run 'python -m build' in the given project root.
    This is also callable from other projects.
    """
    project_root = project_root.resolve()
    if not (project_root / "pyproject.toml").exists():
        raise FileNotFoundError(f"No pyproject.toml found in {project_root}")

    cmd = [sys.executable, "-m", "build"]
    print(f"[piphelper] Running: {' '.join(cmd)} in {project_root}")
    result = subprocess.run(cmd, cwd=str(project_root))
    return result.returncode
